name: Sqlite Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["3.2", "4.0", "4.1", "4.2a1"]
        exclude:
          - django-version: "3.2"
            python-version: "3.11"

          - django-version: "4.0"
            python-version: "3.6"
          - django-version: "4.0"
            python-version: "3.7"
          - django-version: "4.0"
            python-version: "3.11"

          - django-version: "4.1"
            python-version: "3.6"
          - django-version: "4.1"
            python-version: "3.7"
            
          - django-version: "4.2a1"
            python-version: "3.6"
          - django-version: "4.2a1"
            python-version: "3.7"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version != '3.6' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version == '3.6' }}
      uses: deadsnakes/action@v3.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlparse
        pip install -q Django==${{ matrix.django-version }}
    - name: Run Tests
      run: |
        python runtests.py --settings=sql_util.tests.test_sqlite_settings